# vim: filetype=dockerfile

FROM quay.io/centos/centos:stream9

ARG USER_NAME
ARG USER_UID

RUN                                                                                \
    : "${USER_NAME:?Build argument needs to be set and non-empty.}";               \
    : "${USER_UID:?Build argument needs to be set and non-empty.}";                \
    dnf install -y --allowerasing                                                  \
        bash-completion                                                            \
        dnf                                                                        \
        epel-next-release                                                          \
        epel-release                                                               \
        gcc-toolset-12                                                             \
        git                                                                        \
        hostname                                                                   \
        make                                                                       \
        perl                                                                       \
        python3                                                                    \
        sqlite                                                                     \
        sudo                                                                       \
        tmux                                                                       \
        tree                                                                       \
        util-linux-user                                                            \
        yum-utils                                                                  \
        zsh                                                                        \
    && dnf install -y --allowerasing                                               \
        coreutils                                                                  \
        createrepo                                                                 \
        mock                                                                       \
        rpm-build                                                                  \
        rpm-devel                                                                  \
        rpm-sign                                                                   \
        rpmdevtools                                                                \
        rpmlint                                                                    \
    && dnf update -y                                                               \
    && crb enable                                                                  \
    && dnf install -y                                                              \
        mc                                                                         \
        neovim                                                                     \
        python3-neovim

COPY override/ /

RUN                                                                                \
    mkdir -p /usr/local/bin                                                        \
    && passwd -l root                                                              \
    && useradd -m -U -s /usr/bin/zsh -G mock,wheel --uid="$USER_UID" "$USER_NAME"  \
    && passwd -d "$USER_NAME"                                                      \
    && touch "/var/db/sudo/lectured/$USER_NAME"                                    \
    && chmod -R g+rwXs "/home/$USER_NAME"                                          \
    && rm -rf /root

USER $USER_NAME

WORKDIR /home/$USER_NAME

RUN rpmdev-setuptree

CMD tmux
